version: "3.7"
services:
  client:
    build: './client'    
    restart: always
    ports:
      - '3000:3000'
  flask_app:
    build: './flask_app'
    restart: always
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    ports:
      - '5000:5000'
    depends_on:
      - redis

  worker:
    build: './worker'
    restart: always
    pids_limit: 60 # Max number of processes running in the container
    depends_on:
      - redis
      - flask_app


  redis:
    image: 'redis:4-alpine'
    restart: always
    ports:
      - '6379:6379'